module.exports = {
  ProjectID: { name: '', displayName: 'מזהה פרוייקט' },
  Project: { name: '', dispalyName: 'שם פרויקט' },
  PropertyID: { name: '', dispalyName: 'מזהה דירה' },
  ActionType: { name: '', dispalyName: 'סוג פעולה' },
  PropertyTitle: { name: '', dispalyName: 'מס דירה' },
  BuildingTitle: { name: '', dispalyName: 'מס בניין' },
  Address: { name: '', dispalyName: 'כתובת' },
  ModelID: { name: '', dispalyName: 'מזהה דגם' },
  ModelTitle: { name: '', dispalyName: 'שם דגם' },
  Orientation: { name: '', dispalyName: 'כיוון אויר' },
  Rooms: { name: '', dispalyName: 'מס חדרים' },
  Ptype: { name: '', dispalyName: 'תיאור סוג דירה' },
  Floor: { name: '', dispalyName: 'מס קומה' },
  Size: { name: '', dispalyName: 'שטח דירה' },
  SellableSize: { name: '', dispalyName: '' },
  Balcony: { name: '', dispalyName: 'שטח מרפסת' },
  Garden: { name: '', dispalyName: 'דירת גן' },
  VAT: { name: '', dispalyName: 'מעמ' },
  PriceExcVAT: { name: '', dispalyName: 'מחיר ללא מעמ' },
  PriceIncVAT: { name: '', dispalyName: 'מחיר' },
  PriceSQM: { name: '', dispalyName: '' },
  PStatus: { name: '', dispalyName: 'מזהה סטטוס' },
  PropertyStatus: { name: '', dispalyName: 'סטטוס' },
  Currency: { name: '', dispalyName: 'מטבע' },
  Comments: { name: '', dispalyName: 'הערות' },
  Exposure: { name: '', dispalyName: 'כיוון אויר' },
  Discount: { name: '', dispalyName: 'הנחה' },
  PriceAfterDiscount: { name: '', dispalyName: 'מחיר לאחר הנחה' },
  Contract: { name: '', dispalyName: 'חוזה' },
  BuyerName: { name: '', dispalyName: 'שם קונה' },
  CameFrom: { name: '', dispalyName: 'מקור לקוח' },
  BuyerID: { name: '', dispalyName: 'מזהה לקוח' },
  ContractDate: { name: '', dispalyName: 'תאריך חוזה' },
  AgreementDate: { name: '', dispalyName: 'תאריך הסכמה' },
  FinalDate: { name: '', dispalyName: 'תאריך סופי' },
};
